### ISSUE TITLE
Inconsistently getting "Midnight Lizard cannot connect to this page" on lots of sites

### ISSUE THREAD

**Issue by Quenz** [Midnight-Lizard/Midnight-Lizard#215]
https://www.audible.com.au/ for example. It was working at one point, but now it's not. Removing and re-installing the extension seems to work sometimes, but then I inevitably find another site on which I get the same error.

**Comment by pavel-agarkov** [comment]
Thank you for the feedback.
Midnight Lizard does not work on Chrome Web Store, Mozilla Add-ons, New Tab page and all Chrome and Firefox system pages the same way as all other extensions due to security restrictions.
In Chromium based browsers it also does not work on local files until you explicitly allow it.
If some pages were opened before Midnight Lizard installation you might need to refresh them.
It should work on all other regular websites.
If not please reopen this issue with the url where it does not work.
Thank you.

**Comment by Quenz** [comment]
I am using Chrome. Here are some URLs which I currently get the error on (I've tried refreshing them). https://www.audible.com.au/ https://www.audible.com/ https://countn.com/

I've been experiencing this issue for a few days now, and as I said, the issue seems to be resolved sometimes if I remove and then re-install the extension, but I then eventually seem to end up finding another page that it does not work with.

**Comment by pavel-agarkov** [comment]
I cannot reproduce the issue on any of the websites you've mentioned.
And since you have it on different websites - probably it is caused by some other extension interference.
Please check out console logs next time you encounter the same problem.
[How to export logs](https://support.shortpoint.com/support/solutions/articles/1000222881-save-google-chrome-browser-s-console-file)
Thank you.

**Comment by Quenz** [comment]
I've disabled all of my extensions except for Midnight Lizard. [Here](https://gist.github.com/Quenz/ed2fcacbb5d07f3eebc853eceac2c7fc) is the console log for audible.com.au

I tried to do the same thing on countn.com but the log was empty, and I still got the same error in Midnight Lizard.

**Comment by pavel-agarkov** [comment]
It has the same errors in the log even without Midnight Lizard so it has to be something else.
I will try to investigate more. Thank you for your help.

**Comment by chemacortes** [comment]
I had have the same problem. My solution was to edit the storage file "storage-sync.sqlite" with a sqlite browser and delete all registers with the key of midnight-lizar ({8fbc7259-8015-4172-9af1-20e1edfbbd3a}). Starting firefox again, you has some time to go to the panel of midnigth-lizard and remove all global settings. Now, all has working fine.

I suggest to add a config at the firefox extension panel that erases all setting as does the midnight-lizard panel.

**Comment by pavel-agarkov** [comment]
@chemacortes do you mean that the problem is related to some incorrect data in the storage?
I can show 'delete all settings' button as a fourth option in the list of possible causes/solutions.
But probably it would be better to find the real cause and fix it.
Since you know the way to retrieve the data when extension doesn't work.
I would like to receive this data and try to debug with it applied in my browser.
Thank you.

**Comment by Quenz** [comment]
Can someone re-open the issue?

I can't do chemacortes' solution because I use Chrome.

**Comment by chemacortes** [comment]
> @chemacortes do you mean that the problem is related to some incorrect data in the storage?

Yes, I suppose. I had tried several options and customize the style of some pages. One day, the panel advise that the page cannot be configurable. The extension keeps working on the page as I can activate/deactivate the style with the shortkey, but I can't change anyhing.

> I can show 'delete all settings' button as a fourth option in the list of possible causes/solutions.
> But probably it would be better to find the real cause and fix it.
> Since you know the way to retrieve the data when extension doesn't work.
> I would like to receive this data and try to debug with it applied in my browser.
> Thank you.

Sorry, but I don't keep the invalid data file. The file is in the profile directory of firefox and is named "storage-sync.sqlite" (or "storage.sqlite" without sync).

¿Have you see the advise from Mozilla for use LocalStorage?
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage

Firefox will clear data stored by extensions using the localStorage.

**Comment by pavel-agarkov** [comment]
> ¿Have you see the advise from Mozilla for use LocalStorage?

Yes, I've seen it. That's an advice against `Window.localStorage` usage. But I use it only for storing last brightness level to apply global filter during page load before final settings are getting applied. I do use it just because that's the only synchronous storage Api. All user settings are stored in browser.storage.(local | sync). This information is disclosed in the [Extension Privacy Policy](https://midnight-lizard.org/extension-privacy)

**Comment by pavel-agarkov** [comment]
Looks like the problem occurred only when "Original (none)" color scheme was used as a default color scheme. The problem is fixed in v10.3 today. Also I removed entire error message about "...cannot connect..." - now when Midnight Lizard cannot connect to some page it will display and allow to edit default settings instead.
v10.3 is already available for Firefox and will be available for Chromium-based browsers soon (I'm using blue/green deployment and rolling update to the next 10% of the users every day)

**Comment by pavel-agarkov** [comment]
closing by now
feel free to comment if problem appears again

**Comment by czwcasw** [comment]
This is still an issue.
Been getting the problem lately on random pages including cargurus, protonmail, and other pages.

**Comment by pavel-agarkov** [comment]
@czwcasw please describe what exactly is happening.
What browser are you using? Screenshots also might help.

**Comment by devkabiir** [comment]
I had the same issue and fixed it in firefox (sync enabled) by manually clearing all data possibly held by this extension using,

[CAUTION: This will reset the extension so make sure you have some backup available, at least export your custom color schemes if you can. The extension is in a state where it refuses to let me change anything ]
- Go to addons inspection page `about:debugging#/runtime/this-firefox`.
- Find `Midnight Lizard` and click `Inspect`.
- In the newly opened tab, type following lines one-by-one and hit enter.
```js
browser.storage.local.get().then(console.log);
browser.storage.sync.get().then(console.log);
```

It is possible the extension stores data using other APIs as well, but the above two did the trick for me.
